Do not use ocramius/package-versions
infection/infection pull request #1577
Opened 2021-09-13 17:52 UTC by kubawerlos

This PR:

- removes `ocramius/package-versions` from dependencies
- starts using `composer-runtime-api` as [suggested](https://github.com/composer/composer/issues/10034#issuecomment-901888729) by @Seldaek

2021-09-13 18:16 UTC, Seldaek requested changes

2021-09-13 18:16 UTC, Seldaek commented on src/Process/Factory/InitialTestsRunProcessFactory.php
> +        if (method_exists($process, 'inheritEnvironmentVariables') && version_compare((string) InstalledVersions::getReference('symfony/console'), 'v4.4', '<')) {
Should be getVersion

2021-09-13 18:16 UTC, Seldaek commented on src/Console/Application.php
> +            $version = (string) InstalledVersions::getReference(self::PACKAGE_NAME);
Should be getVersion

2021-09-13 18:16 UTC, Seldaek commented on src/Process/Factory/MutantProcessFactory.php
> +        if (method_exists($process, 'inheritEnvironmentVariables') && version_compare((string) InstalledVersions::getReference('symfony/console'), 'v4.4', '<')) {
Should be getVersion

2021-09-14 05:21 UTC, maks-rafalko commented on src/Command/ConfigureCommand.php
> +            $version = InstalledVersions::getReference(Application::PACKAGE_NAME);
seems like this breaks the tests

2021-09-15 05:11 UTC, maks-rafalko approved these changes
Thank you @kubawerlos

2021-09-15 05:11 UTC, merged

2021-09-19 11:17 UTC, maks-rafalko commented
compiled PHAR now fails with

```
PHP Fatal error:  Uncaught Error: Class "_HumbugBox11d54ac50db9\Composer\InstalledVersions" not found in phar:///home/maksrafalko/apps/infection/build/infection.phar/src/Console/Application.php:36
Stack trace:
#0 phar:///home/maksrafalko/apps/infection/build/infection.phar/bin/infection(71): _HumbugBox11d54ac50db9\Infection\Console\Application->__construct()
#1 /home/maksrafalko/apps/infection/build/infection.phar(14): require('phar:///home/ma...')
#2 {main}
  thrown in phar:///home/maksrafalko/apps/infection/build/infection.phar/src/Console/Application.php on line 36

```

2021-09-19 18:16 UTC, maks-rafalko commented
Reverted due to fatal error above